version: '3.3'
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile.scratch
    ports:
      - "8080:8080"  
    expose: ["8080"]  
  site:
    container_name: site
    build:
      context: ./site
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    links: 
      - api  
    depends_on:
      - api  